<h1 style="padding-top: 25px;padding-bottom: 25px;text-align: left; padding-left: 10px; background-color: #DDDDDD; 
    color: black;"> <img style="float: left; padding-right: 10px; width: 45px" src="https://raw.githubusercontent.com/Harvard-IACS/2018-CS109A/master/content/styles/iacs.png"> AC295: Advanced Practical Data Science </h1>

## Project: News Analytics for Stock Return Prediction

**Harvard University, Fall 2020**  
**Instructors**: Pavlos Protopapas  

### **Team: $\alpha\beta normal$ $Distri\beta ution$**
#### **Roht Beri, Eduardo Peynetti, Jessica Wijaya, Stuart Neilson**

# Finetuning Fin-BERT on combined and reduced FinnHub and Tiingo Dataset 



**Using -1, 0, 1 as target with 0 being no information from Loughram McDonald Model and , -1 representing above or below market returns**

## Disks

### Connect Google Drive

In [1]:
from google.colab import drive

drive.mount('/content/drive', force_remount=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Libraries

### Install Packages

In [2]:
!pip3 install transformers
!pip3 install --upgrade pymongo[srv]==3.10.1
!pip3 install dask[dataframe]

Requirement already up-to-date: pymongo[srv]==3.10.1 in /usr/local/lib/python3.6/dist-packages (3.10.1)


### Imports

In [3]:
import os
import ast
import requests
import tarfile
import tempfile
import zipfile
import shutil
import csv
import json
import time
import sys
import subprocess
import logging
import pickle

import pymongo
import bson
import dns

import numpy as np
import pandas as pd
import dask.dataframe as dd
import matplotlib.pyplot as plt

import tensorflow as tf
import tensorflow_addons as tfa
import tensorflow_hub as hub

from tensorflow import keras
from tensorflow.python.keras import backend as K
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras import layers

from collections import Counter
from glob import glob
from threading import Thread

from pytz import timezone
from bson import BSON, ObjectId
from pymongo import MongoClient
from tabulate import tabulate
from tqdm.notebook import tqdm, trange
from datetime import datetime, timedelta, date, time
from dateutil.parser import isoparser

from transformers import BertTokenizer, TFBertForSequenceClassification, AutoModel

%matplotlib inline

## Variables

### Useful Constants and Variables

In [4]:
# Set google drive path for pipeline storage
PATH = '/content/drive/MyDrive/abnormal-distribution-project-data/headlines/'
TICKERS_PATH = '/content/drive/MyDrive/abnormal-distribution-project-data/components/sp1500.csv'
IND_PATH = '/content/drive/MyDrive/abnormal-distribution-project-data/components/industries.csv'
IND_GROUP_PATH = '/content/drive/MyDrive/abnormal-distribution-project-data/components/industry_groups.csv'
SECTOR_PATH = '/content/drive/MyDrive/abnormal-distribution-project-data/components/sectors.csv'
BERT_HIDDEN_PATH = '/content/drive/MyDrive/abnormal-distribution-project-data/headlines/bert_hs/'

#Helpful Constants
START = datetime(2000,1,1)
END = datetime.now()
WINDOW = 365
AUTOTUNE = tf.data.experimental.AUTOTUNE

# Mongo Atlas keys & host name
PASSWORD = '47PXdQpbJKFTLGTJ'
DBNAME = 'abnormalDistribution'
COLLECTION = 'tiingo'
HOST = f'mongodb+srv://abnormal-distribution:{PASSWORD}@cluster0.friwl.mongodb.net/{DBNAME}?retryWrites=true&w=majority'
print(HOST)

# Pipeline variables
batch_size = 128
prefetch = AUTOTUNE

# BERT Model
bert_model = 'ipuneetrathore/bert-base-cased-finetuned-finBERT' #'bert-base-uncased'
cased = False

mongodb+srv://abnormal-distribution:47PXdQpbJKFTLGTJ@cluster0.friwl.mongodb.net/abnormalDistribution?retryWrites=true&w=majority


In [5]:
#MASTER_PATH = '/content/drive/MyDrive/abnormal-distribution-project-data/lean/master.p'
TRAIN_PATH = '/content/drive/MyDrive/abnormal-distribution-project-data/lean/train.p'
VALID_PATH = '/content/drive/MyDrive/abnormal-distribution-project-data/lean/valid.p'
TEST_PATH = '/content/drive/MyDrive/abnormal-distribution-project-data/lean/test.p'


with open(TRAIN_PATH,'rb') as pkl_file:
  train_df = pickle.load(pkl_file)
with open(VALID_PATH,'rb') as pkl_file:
  valid_df = pickle.load(pkl_file)
with open(TEST_PATH,'rb') as pkl_file:
  test_df = pickle.load(pkl_file)

In [6]:
train_df.shape

(1408396, 12)

In [7]:
valid_df.shape

(459386, 12)

In [8]:
test_df.shape

(1856673, 12)

### Get Tickers and Sectors

In [9]:
tickers = pd.read_csv(TICKERS_PATH).values.flatten()
sectors = pd.read_csv(SECTOR_PATH).sector.values

#industry = pd.read_csv(IND_PATH).industry.values
#ind_group = pd.read_csv(IND_GROUP_PATH).industry_group.values

tickers.sort()
sectors.sort()

## TFRecords

### Utils for Creating TFRecords

In [10]:
# The following functions can be used to convert a value to a type compatible
# with tf.train.Example.
# Credit: https://www.tensorflow.org/tutorials/load_data/tfrecord

def _bytes_feature(value):
  """Returns a bytes_list from a string / byte."""
  if isinstance(value, type(tf.constant(0))):
    value = value.numpy() # BytesList won't unpack a string from an EagerTensor.
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _float_feature(value):
  """Returns a float_list from a float / double."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _int64_feature(value):
  """Returns an int64_list from a bool / enum / int / uint."""
  return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

In [11]:
# Function get returns 
def get_return(ticker, d):

  #date = pd.to_datetime(date).tz_convert('US/Eastern')
  d = datetime.strptime(d[0:19], "%Y-%m-%dT%H:%M:%S")
  d.replace(tzinfo=timezone('UTC'))
  d.astimezone(timezone('US/Eastern'))
  date_close = d
  date_open = d

  if date_open.hour >= 9:
    date_open = date_open + timedelta(days=1)

  if date_close.hour >= 16:
    date_close = date_close + timedelta(days=1)

  date_open = calendar.loc[date_open.date()].values[0]
  date_close = calendar.loc[date_close.date()].values[0]

  try:

    return_open = targets.loc[(date_open, ticker.lower())]['1D_target_open']
    return_close = targets.loc[(date_close, ticker.lower())]['1D_target_close']

  except:

    return_open = np.nan
    return_close = np.nan

  if  (not isinstance(date_open, date)) | (not isinstance(date_close, date)):
    print(date_open)
    print(date_close)

  return return_open, str(date_open), return_close, str(date_close)
    


In [12]:
# Function to create TFRecord Sample for writing
def get_tf_record(item, tokenizer):

    id = item['id']
    t_open = item['target_open']
    t_close = item['target_close']

    description = item['text']
    description_token = tokenizer.encode_plus(
        description, 
        add_special_tokens = True, # add [CLS], [SEP]
        max_length = 512, # max length of the text that can go to BERT (<=512)
        padding='max_length',
        return_attention_mask = True, # add attention mask to not focus on pad tokens
        truncation='longest_first',
        return_tensors="tf"
    )
    description_input = description_token['input_ids'].numpy().tostring()
    description_type = description_token['token_type_ids'].numpy().tostring()
    description_attention = description_token['attention_mask'].numpy().tostring()

    # Create tf.train.Example
    feature={
        '_id' : _int64_feature(id),
        'input_ids': _bytes_feature(description_input),
        'token_type_ids': _bytes_feature(description_type),
        'attention_mask': _bytes_feature(description_attention), 
        'return_open': _int64_feature(t_open),
        'return_close': _int64_feature(t_close),
    }
    features=tf.train.Features(feature=feature)
    example = tf.train.Example(features=features)

    return example

In [13]:
# Creates shard for the given ticker
def write_tfrecord(df, shard_path, tokenizer):
    
    # Tokenize the data and parse the TF Record
    examples = df.apply(get_tf_record, axis=1, args=(tokenizer,))

    # TFRecord writer initialized
    with tf.io.TFRecordWriter(shard_path) as writer:
        
        # Write to TFRecords
        for example in tqdm(examples):
            
            # Wrtie the TFRecord
            writer.write(example.SerializeToString())

In [14]:
# Function to create TFRecords for the dataset
def create_TFRecords(
    train_path=TRAIN_PATH, valid_path=VALID_PATH, 
    test_path=TEST_PATH, path=PATH
):
    # Setup folders
    if not os.path.exists(path + 'tf_records_lean'):
        os.mkdir(path + 'tf_records_lean')


    # Setup paths
    done_path = path + 'tf_records_lean/*.records'
    shard_path = path + "tf_records_lean/{}_{:02d}.records"

    # Files alread done   
    records_done = []
    records_done.extend(glob(done_path))

    #Initalize BERT Tokenizer
    tokenizer = BertTokenizer.from_pretrained(bert_model, do_lower_case=cased)

    # List of data paths
    path_set = [train_path, valid_path, test_path]
    path_type = ['train', 'valid', 'test']

    # Max number of records ina shard
    max_num_records = 100000

    # Run loop over three paths
    for i, data_path in tqdm(enumerate(path_set)):
        
        # Read the data into pandas
        with open(data_path,'rb') as pkl_file:
            df = pickle.load(pkl_file)

        num_records = df.shape[0]
        num_shards = num_records//max_num_records
        num_shards += min(1, num_records % max_num_records)

        print('Processing {} data'.format(path_type[i]))
        for j in trange(num_shards):
            # Path for the shard
            temp_path = shard_path.format(path_type[i], j)
            
            # Check if the shard already exists
            if os.path.exists(temp_path):
                continue
            
            # Start and the end of the shard
            start = j * max_num_records
            end = min(num_records, (j+1)*max_num_records)

            # Dataframe slice
            temp_df = df.iloc[start : end]

            # Create the TFRecord
            write_tfrecord(temp_df, temp_path, tokenizer)

### Create TFRecords Dataset

In [15]:
#shutil.rmtree('/content/drive/MyDrive/abnormal-distribution-project-data/headlines/tf_records_monthly_fin')

In [16]:
# Create TFRecords for Stocks
create_TFRecords()

Processing train data



Processing valid data



Processing test data


### Read TFRecords Dataset

In [17]:
# Check data integrity
tick_path = PATH + 'tf_records_lean/*.records'

files = glob(tick_path)
i = 0
for file in tqdm(files):
    raw_dataset = tf.data.TFRecordDataset(file)
    try:
        for raw_record in raw_dataset.take(10):
            example = tf.train.Example()
            example.ParseFromString(raw_record.numpy())
            example = example.features.feature['_id']
        
        del raw_dataset
    except:
        #os.remove(file)
        print('file in problem: ', file)
        i += 1

if i:
    print(f"{i} files were deleted, please rerun Create TFRecords")
else:
    print("TFRecords are in good shape")


TFRecords are in good shape


In [18]:
filenames = ['/content/drive/MyDrive/abnormal-distribution-project-data/headlines/tf_records_lean/train_02.records']
raw_dataset = tf.data.TFRecordDataset(filenames)
raw_dataset

<TFRecordDatasetV2 shapes: (), types: tf.string>

In [19]:
for raw_record in raw_dataset.take(1):
    example = tf.train.Example()
    example.ParseFromString(raw_record.numpy())
    print(example)

features {
  feature {
    key: "_id"
    value {
      int64_list {
        value: 3903159
      }
    }
  }
  feature {
    key: "attention_mask"
    value {
      bytes_list {
        value: "\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\

In [20]:
# Create a dictionary describing the features.
features={
        '_id': tf.io.FixedLenFeature([], tf.int64), 
        'input_ids': tf.io.FixedLenFeature([], tf.string),
        'token_type_ids': tf.io.FixedLenFeature([], tf.string),
        'attention_mask': tf.io.FixedLenFeature([], tf.string), 
        'return_open': tf.io.FixedLenFeature([], tf.int64),
        'return_close': tf.io.FixedLenFeature([], tf.int64),
    }

def _parse_image_function(example_proto):
  # Parse the input tf.train.Example proto using the dictionary above.
  return tf.io.parse_single_example(example_proto, features)

parsed_image_dataset = raw_dataset.map(_parse_image_function)
parsed_image_dataset

<MapDataset shapes: {_id: (), attention_mask: (), input_ids: (), return_close: (), return_open: (), token_type_ids: ()}, types: {_id: tf.int64, attention_mask: tf.string, input_ids: tf.string, return_close: tf.int64, return_open: tf.int64, token_type_ids: tf.string}>

In [21]:
i = 0
for data in parsed_image_dataset:
    input_ids = tf.io.decode_raw(data['input_ids'], tf.int32)
    print(data['return_open'].numpy())
    print(data['return_close'].numpy())
    print(data['_id'])
    print(input_ids.numpy()[:10])
    print(input_ids.numpy().shape)
    break

0
0
tf.Tensor(3903159, shape=(), dtype=int64)
[  101 13876  6778 17244 14719  3561   119   113  5883 12649]
(512,)


## Pipeline

### Utils for BERT Pieline

In [22]:
# Function to parse data features
def _parse_features_function(example):
    # Parse the input tf.train.Example proto using the dictionary above.
    tf_records_features = {
        '_id': tf.io.FixedLenFeature([], tf.int64), 
        'input_ids': tf.io.FixedLenFeature([], tf.string),
        'token_type_ids': tf.io.FixedLenFeature([], tf.string),
        'attention_mask': tf.io.FixedLenFeature([], tf.string), 
        'return_open': tf.io.FixedLenFeature([], tf.int64),
        'return_close': tf.io.FixedLenFeature([], tf.int64),
    }
    return tf.io.parse_single_example(example, tf_records_features)


# Structure the data for training returns
def structure_data_open(data):
    id = data['_id']
    input_ids = tf.io.decode_raw(data['input_ids'], tf.int32)
    attention_mask = tf.io.decode_raw(data['attention_mask'], tf.int32)
    token_type_ids = tf.io.decode_raw(data['token_type_ids'], tf.int32)
    open = data['return_open'] + 1
    close = data['return_close'] + 1
    
    return ((input_ids, token_type_ids, attention_mask), open)

# Structure the data for training sentiments 
def structure_data_close(data):
    id = data['_id']
    input_ids = tf.io.decode_raw(data['input_ids'], tf.int32)
    attention_mask = tf.io.decode_raw(data['attention_mask'], tf.int32)
    token_type_ids = tf.io.decode_raw(data['token_type_ids'], tf.int32)
    open = data['return_open']
    close = data['return_close']

    return ((input_ids, token_type_ids, attention_mask), close)

In [25]:
def generate_multiple_pipelines(
    train = True, test = False, open=True, path=PATH, batch_size=batch_size
):
    print("Generating Pipeline....")

    if open:
        func = structure_data_open
    else:
        func = structure_data_close

    if train:
        tfrecords_pattern_path = path + "tf_records_lean/train_*.records"
    elif test:
        tfrecords_pattern_path = path + "tf_records_lean/test_*.records"
    else:
        tfrecords_pattern_path = path + "tf_records_lean/valid_*.records"

    options = tf.data.Options()
    options.experimental_deterministic = False
    
    train_files = tf.io.matching_files(tfrecords_pattern_path)
    
    train_shards = tf.data.Dataset.list_files(train_files, shuffle=len(train_files))
    #train_shards = tf.data.Dataset.from_tensor_slices(train_shards)

    train = train_shards.interleave(tf.data.TFRecordDataset, cycle_length=12)
    train = train.with_options(options)
    train = train.map(_parse_features_function, num_parallel_calls=AUTOTUNE)
    train = train.map(func, num_parallel_calls=AUTOTUNE)
    train = train.batch(batch_size)
    train = train.shuffle(buffer_size=512)
    #train = train.cache().prefetch(prefetch)

    return train

### Test Pipeline

In [26]:
tickers_data = generate_multiple_pipelines()
tickers_data

Generating Pipeline....


<ShuffleDataset shapes: (((None, None), (None, None), (None, None)), (None,)), types: ((tf.int32, tf.int32, tf.int32), tf.int64)>

In [27]:
for item in tickers_data.take(1):
    print('answer: ', item[1][0].numpy())
    print()
    print('input_ids: ',item[0][0][0].numpy().shape)

answer:  1

input_ids:  (512,)


In [28]:
for item in tickers_data.take(1):
    print(item)

((<tf.Tensor: shape=(128, 512), dtype=int32, numpy=
array([[  101,  1135,   112, ...,     0,     0,     0],
       [  101, 11801,  1456, ...,     0,     0,     0],
       [  101, 23069, 22347, ...,     0,     0,     0],
       ...,
       [  101,   153,  2559, ...,     0,     0,     0],
       [  101,  1752,  7268, ...,     0,     0,     0],
       [  101,   156, 22705, ...,     0,     0,     0]], dtype=int32)>, <tf.Tensor: shape=(128, 512), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, <tf.Tensor: shape=(128, 512), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>), <tf.Tensor: shape=(128,), dtype=int64, nump

## BERT Model

### Utils to build model to get BERT Sentiment with finetuning

In [ ]:
# Function to train and finetune
def finetune_BERT(open=True, path=BERT_HIDDEN_PATH):
        
    checkpoint_filepath = path + 'monthly_fin/model_checkpoints'
    
    # Clear Backend
    K.clear_session()

    # Compile Options
    optimizer = tf.keras.optimizers.Adam(learning_rate=3e-5)
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    metrics = ['accuracy']

    # Check if previouly trained model is there
    if os.path.exists(checkpoint_filepath):
        bert = AutoModel.from_pretrained(path)
    else:
        if not os.path.exists(path+'monthly_fin'):
            os.mkdir(path+'monthly_fin')
        # BERT classification model
        bert = TFBertForSequenceClassification.from_pretrained(
            bert_model,
            from_pt = True,
        )

    # BERT last layer is trainable
    bert.trainable = False
    bert.layers[2].trainable=True
    
    # Compile the Model
    bert.compile(optimizer=optimizer, loss = loss, metrics=metrics)

    # Callbacks
    model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
        filepath=checkpoint_filepath,
        save_weights_only=True,
        mode='max',
        save_freq=1000,
    )
    
    # Training pipeline
    train = generate_multiple_pipelines(open=open)
   
   # Validation pipeline
    valid = generate_multiple_pipelines(train=False, open=open)

    # Finetune the model
    bert.fit(
        train, 
        epochs=1,
        validation_data=valid,
        verbose=1,
        callbacks = [model_checkpoint_callback]
    )

    #save the model
    path = path + 'monthly_fin/model'
    bert.save_pretrained(path)

    # Return the model
    return bert

### Train/Finetune Bert

In [ ]:
# Train BERT
model = finetune_BERT()

## Scrap

In [ ]:
# Connect to MongoDB
client = pymongo.MongoClient(HOST)
db = client[DBNAME]
news_collection = db[COLLECTION]

In [ ]:
# Space for testing/experimentation

In [ ]:
# Terminate the MongoDB Session
client.close()